# Generated by Django 3.2.7 on 2021-11-15 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20211031_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 8, 39, 29, 304381, tzinfo=utc), verbose_name='ending date'),
        ),
    ]
