# Generated by Django 3.2.7 on 2021-11-15 09:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_question_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 16, 9, 14, 0, 555323, tzinfo=utc), verbose_name='ending date'),
        ),
    ]
